### ISSUE TITLE
Уточнение описания детали

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#26]
Часто бывает, что описание детали не соответствует действительности. Поэтому необходимо, чтобы результат запроса покрывала админская информация.

Админу нужна такая форма:
Заголовок: Уточнение описания детали
Поле1: Номер
Поле2: Описание
Поле3: Вес
Поле4: Объем
Кнопка Применить

Пример: 
Вносим такие данные
Поле1: 8881027802LK
Поле2: Гламурный ремень безопасности
Поле3: 1,395
Поле4: 0,554

Теперь при поиске "8881027802LK" нам будет выдавать не
HYUNDAI  8881027802LK  SEAT BELT ASSY-FRONT,LH  .554  1.095  4  164,74  ODES1  1 
а вот это: 
HYUNDAI  8881027802LK  Гламурный ремень безопасности  0,554  1.395  4  164,74  ODES1  1

**Comment by Podovzhniy** [comment]
По сути создаем табличку алиасов аналогичную по структуре Part и делаем редактирование для нее.
А при поисковой выдаче используем данные из этой таблички.
