### ISSUE TITLE
Таблица замен

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#28]
Два поля:
Номер Детали1 и Номер Детали2

Т.е. если мы ищем Номер Детали1, то в результат выдачи подтягивается и Номер Детали2

**Comment by Podovzhniy** [comment]
Делаем загрузку и выгрузку этой таблички из экселевского файла.
В поисковой выдаче добавляем результаты для замен.
Может нужен какой-то атрибут указывающий, что это замена ?
