### ISSUE TITLE
Странно отображает скрипт с  номерами страниц

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#32]
"Страница 1 из 1" и ниже опять 1 в квадрате...

**Comment by Podovzhniy** [comment]
А где именно это?
На какой страничке?

**Comment by Koshkareov** [comment]
http://ap.hg.com.ua/PartAlias

**Comment by Koshkareov** [comment]
У меня часто выдает "Страница 1 из 1" и ниже еще одна единица в синем квадрате. Это должно появляться при кол-ве страниц более 2-х и без дублирования информации.
