### ISSUE TITLE
Нужно поправить навигацию для возврата из наценок

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#33]
РЕЕСТР ПОЛЬЗОВАТЕЛЕЙ >> НАЦЕНКИ ДЛЯ ПОЛЬЗОВАТЕЛЯ ob-ok@ukr.net >> Изменить >> Назад в наценки пользователя !!! Попадаем в РЕЕСТР ПОЛЬЗОВАТЕЛЕЙ !!!
а должны возвращаться в "НАЦЕНКИ ДЛЯ ПОЛЬЗОВАТЕЛЯ"
Аналогично с переходом из формы удаления.

**Comment by Podovzhniy** [comment]
Готово
