### ISSUE TITLE
Импорт заказа из XLSX-файла для Админа

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#35]
Отличие от клиентского в том, что тут среди поставщиков будут участвовать в тендере "скрытые поставщики", т.е. те, кто предоставил единоразовое предложение под конкретный заказ.
Генерируется предложение в формате XLSX с такими полями:
Бренд, Номер, Описание, Кол-во, Цена

Если клиент согласен, то предзаказу устанавливается подтверждение и создается заказ. Админу генерируются файлы-заказы с разбивкой по поставщикам. Ну и статусы...

**Comment by Podovzhniy** [comment]
Нужно немного облагородить доп параметры в форме поиска
