### ISSUE TITLE
Странно работает Поиск позиции

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#50]
К примеру, ищем 61784B4040B2 из формы, получаем два варианта: 3,64 OAE1 и 3,74 MAHM, при поиске этой же позиции через файл, мы получаем 3,74 MAHM (т.е. более дорогой вариант!!!) Подозреваю, что баг в сортировке, т.е. сначала сортируем по цене, а уже потом по сроку достаки.

**Comment by Podovzhniy** [comment]
При-аттач  плз.  сюда файл, который использовался для поиска.

**Comment by Podovzhniy** [comment]
Нашел, воспроизвел, исправил.
