### ISSUE TITLE
Трабла после добавления в корзину

### ISSUE THREAD

**Issue by Koshkareov** [Podovzhniy/AutoParts#9]
После добавления в корзину, поиск выдает предупреждение "Для поиска более 1-й позиции требуется авторизация", хотя я остаюсь залогиненым.

**Comment by Koshkareov** [comment]
![2016-05-31 11 03 27](https://cloud.githubusercontent.com/assets/19567131/15667518/5a6a5fd0-271f-11e6-931d-f3cab99a46ff.png)

**Comment by Koshkareov** [comment]
Попробовал перелогиниться - не помогло! Это серьезный баг и без его решения я не могу дальше тестировать.

**Comment by Podovzhniy** [comment]
Проверил, воспроизвел. Попробую поправить .

**Comment by Podovzhniy** [comment]
Запутался с isuue #2 
Пока сделал что без регистрации выдается  - "Для поиска более 1-й позиции требуется авторизация"
а с регистрацией - "Результат для поиска N позиций из M "
